apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-log-analyzer
  labels:
    app: ai-log-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-log-analyzer
  template:
    metadata:
      labels:
        app: ai-log-analyzer
    spec:
      containers:
        - name: ai-log-analyzer
          image: devops734/ai-log-analyzer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"